/**
 * Seed script for Andes 360 Capital
 * Populates the database with ~60 high-quality small-cap mining companies (< $2B)
 * Run: cd backend && npm run seed
 */

import Database from 'better-sqlite3';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const dbPath = path.join(__dirname, '..', 'backend', 'data', 'andes360.db');
const db = new Database(dbPath);

const companies = [
  // === ANDES FOCUS (strong representation) ===
  { name: "Andean Precious Metals", ticker: "ANPMF", type: "Silver", category: "Producer", risk: "High", market_cap: 741000000, above_50dma: 1, current_price: 1.48, comment: "Bolivia silver-gold producer with rapid growth at San Bartolomé. Strong leverage to silver.", pros: "Pure-play Andes silver producer, production ramp, undervalued vs peers", cons: "Bolivia political risk, single primary jurisdiction" },
  { name: "Rio2 Limited", ticker: "RIOFF", type: "Gold", category: "Developer", risk: "High", market_cap: 348000000, above_50dma: 1, current_price: 0.52, comment: "Advancing the Fenix gold project in Peru. Low capex, high-grade, near-term production.", pros: "Permits in hand, excellent AISC profile, strong Peruvian team", cons: "Development-stage, needs financing, single asset" },
  { name: "Lundin Gold (small-cap view)", ticker: "LUGDF", type: "Gold", category: "Producer", risk: "Medium", market_cap: 1850000000, above_50dma: 1, current_price: 7.85, comment: "Fruta del Norte in Ecuador — one of the highest-grade gold mines globally. Exceptional margins.", pros: "World-class asset, low costs, strong FCF, dividend growth", cons: "Single asset concentration, Ecuador political perception" },
  
  // === SILVER JUNIORS & PRODUCERS ===
  { name: "Apollo Silver", ticker: "APGOF", type: "Silver", category: "Developer", risk: "High", market_cap: 148000000, above_50dma: 1, current_price: 0.31, comment: "High-grade silver project in Mexico. Strong exploration results and clean balance sheet.", pros: "High-grade, large resource, experienced team, low enterprise value", cons: "Early development stage, Mexico permitting timeline" },
  { name: "Vizsla Silver", ticker: "VZLAF", type: "Silver", category: "Developer", risk: "High", market_cap: 285000000, above_50dma: 1, current_price: 1.12, comment: "Panuco project, Mexico. High-grade silver vein district with district-scale potential.", pros: "Exceptional grades, near-surface, strong metallurgy", cons: "Exploration risk, requires significant drilling" },
  { name: "Endeavour Silver", ticker: "EXK", type: "Silver", category: "Producer", risk: "High", market_cap: 980000000, above_50dma: 0, current_price: 4.85, comment: "Mexican silver producer with Terronera development project. Operating leverage to silver price.", pros: "Production growth via Terronera, solid exploration pipeline", cons: "Mexico jurisdiction risk, historical cost inflation" },
  { name: "MAG Silver", ticker: "MAG", type: "Silver", category: "Producer", risk: "Medium", market_cap: 1390000000, above_50dma: 1, current_price: 13.80, comment: "50% of Juanicipio (Mexico) with Fresnillo. World-class high-grade silver mine.", pros: "Tier-1 asset, strong partner, cash flow inflection", cons: "Mexico mining law uncertainty, 50% non-operator" },
  { name: "Aya Gold & Silver", ticker: "AYASF", type: "Silver", category: "Producer", risk: "High", market_cap: 920000000, above_50dma: 1, current_price: 8.45, comment: "Zgounder silver mine in Morocco. High-grade, expanding production rapidly.", pros: "High-grade, low-cost, excellent management, growth trajectory", cons: "North Africa jurisdiction, single main asset" },
  { name: "Discovery Silver", ticker: "DSVSF", type: "Silver", category: "Developer", risk: "High", market_cap: 1650000000, above_50dma: 1, current_price: 1.95, comment: "Cordero project — one of the largest undeveloped silver deposits in Mexico.", pros: "Huge scale, low strip, strong economics, silver bull case", cons: "Long timeline, Mexico risk, large financing requirement" },
  { name: "Guanajuato Silver", ticker: "GSVRF", type: "Silver", category: "Producer", risk: "High", market_cap: 185000000, above_50dma: 1, current_price: 0.28, comment: "Reviving historic silver districts in Mexico. Multiple operating mines.", pros: "Low capex restarts, district consolidation strategy", cons: "Small scale, execution risk on multiple fronts" },
  { name: "Outcrop Silver", ticker: "OCGCF", type: "Silver", category: "Explorer", risk: "High", market_cap: 92000000, above_50dma: 1, current_price: 0.19, comment: "High-grade silver-gold in Colombia. Santa Ana project advancing.", pros: "Very high grades, Colombia improving jurisdiction", cons: "Early stage, Colombia risk premium" },

  // === GOLD DEVELOPERS & SMALL PRODUCERS ===
  { name: "Revival Gold", ticker: "RVLGF", type: "Gold", category: "Developer", risk: "High", market_cap: 145000000, above_50dma: 1, current_price: 0.42, comment: "Beartrack-Arnett gold project in Idaho. Large resource, heap-leach potential.", pros: "Idaho (safe jurisdiction), large oxide resource, experienced team", cons: "Development stage, permitting timeline" },
  { name: "McEwen Mining", ticker: "MUX", type: "Gold", category: "Producer", risk: "High", market_cap: 820000000, above_50dma: 1, current_price: 9.85, comment: "Gold & silver producer with assets in USA, Canada, Mexico, Argentina. High beta.", pros: "Diversified jurisdictions, exploration upside at Los Azules copper too", cons: "High volatility, mixed operational history" },
  { name: "New Gold", ticker: "NGD", type: "Gold", category: "Producer", risk: "Medium", market_cap: 1380000000, above_50dma: 1, current_price: 2.15, comment: "Canadian gold producer with New Afton and Rainy River. Copper by-product.", pros: "Canada focus, strong cash flow, copper credits", cons: "Some higher cost assets, moderate scale" },
  { name: "Galiano Gold", ticker: "GAU", type: "Gold", category: "Producer", risk: "Medium", market_cap: 680000000, above_50dma: 1, current_price: 1.65, comment: "Asanko Gold Mine in Ghana (50% JV with Gold Fields). Strong cash generation.", pros: "Low cost, Ghana improving, strong JV partner", cons: "Africa risk, JV complexity" },
  { name: "Gold Resource", ticker: "GORO", type: "Gold", category: "Producer", risk: "High", market_cap: 165000000, above_50dma: 0, current_price: 0.68, comment: "Don David Gold Mine in Mexico + Nevada exploration. Small but cash-flow positive.", pros: "Producing, dividend history, low enterprise value", cons: "Mexico risk, small production base" },
  { name: "Americas Gold & Silver", ticker: "USAS", type: "Silver", category: "Producer", risk: "High", market_cap: 125000000, above_50dma: 1, current_price: 0.32, comment: "Relief Canyon (Nevada) + Cosalá (Mexico). Silver-gold producer.", pros: "USA + Mexico mix, silver leverage", cons: "Operational challenges historically, dilution risk" },

  // === COPPER SMALL-CAP / DEVELOPERS ===
  { name: "Taseko Mines", ticker: "TGB", type: "Copper", category: "Producer", risk: "Medium", market_cap: 920000000, above_50dma: 1, current_price: 2.85, comment: "Gibraltar copper mine (Canada) + Florence copper project (Arizona). Strong growth.", pros: "Florence is low-capex, high return, USA jurisdiction", cons: "Canada + USA permitting, copper price beta" },
  { name: "Ero Copper", ticker: "ERO", type: "Copper", category: "Producer", risk: "Medium", market_cap: 1580000000, above_50dma: 1, current_price: 16.40, comment: "High-grade copper-gold in Brazil. Excellent operational performance.", pros: "Low costs, high margins, Brazil copper growth story", cons: "Brazil exposure, smaller size" },
  { name: "Faraday Copper", ticker: "CPPKF", type: "Copper", category: "Developer", risk: "High", market_cap: 285000000, above_50dma: 1, current_price: 0.95, comment: "Copper Creek project in Arizona. Large resource with significant exploration upside.", pros: "USA copper, large resource, strong team", cons: "Long development timeline, large capex required" },
  { name: "Arizona Sonoran Copper", ticker: "ASCUF", type: "Copper", category: "Developer", risk: "High", market_cap: 320000000, above_50dma: 1, current_price: 1.45, comment: "Cactus project in Arizona. Brownfield copper with strong economics.", pros: "Arizona (best USA jurisdiction), brownfield, strong economics", cons: "Still pre-production, financing ahead" },
  { name: "Hudbay Minerals", ticker: "HBM", type: "Copper", category: "Producer", risk: "Medium", market_cap: 2650000000, above_50dma: 1, current_price: 7.20, comment: "Copper-gold producer in Peru & Canada. Snow Lake + Constancia.", pros: "Diversified, good copper-gold mix, Peru assets", cons: "Peru community risk, moderate scale" },

  // === ROYALTY & STREAMING (SMALL/MID) ===
  { name: "Sandstorm Gold", ticker: "SAND", type: "Diversified", category: "Royalty", risk: "Medium", market_cap: 1720000000, above_50dma: 1, current_price: 5.65, comment: "Diversified royalty/streaming portfolio. Gold, copper, and critical minerals exposure.", pros: "Asset-light, growing portfolio, strong deal flow", cons: "Lower leverage to metal prices than operators" },
  { name: "Osisko Gold Royalties", ticker: "OR", type: "Diversified", category: "Royalty", risk: "Low", market_cap: 1850000000, above_50dma: 1, current_price: 17.80, comment: "High-quality gold royalty company with Canadian focus and strong balance sheet.", pros: "Premium assets, low risk, excellent management", cons: "Premium valuation, less torque than juniors" },

  // === CRITICAL MINERALS & URANIUM / RARE EARTHS ===
  { name: "Ucore Rare Metals", ticker: "UURAF", type: "Critical Minerals", category: "Developer", risk: "High", market_cap: 145000000, above_50dma: 1, current_price: 0.85, comment: "Bokan Mountain rare earth project (Alaska) + RapidSX separation technology.", pros: "USA critical minerals, government support potential, tech edge", cons: "Early stage, rare earth price volatility" },
  { name: "Energy Fuels", ticker: "UUUU", type: "Uranium", category: "Producer", risk: "High", market_cap: 1450000000, above_50dma: 1, current_price: 6.85, comment: "Leading US uranium producer with rare earths and vanadium. White Mesa mill.", pros: "USA uranium leader, diversified, strategic asset", cons: "Uranium price still recovering, policy dependent" },
  { name: "Uranium Energy Corp", ticker: "UEC", type: "Uranium", category: "Producer", risk: "High", market_cap: 1280000000, above_50dma: 1, current_price: 5.45, comment: "US-focused uranium developer/producer with significant resources.", pros: "USA assets, large resource base, ISR low-cost potential", cons: "Development risk, uranium sector volatility" },

  // === MORE GOLD & SILVER SMALL CAPS ===
  { name: "Coeur Mining", ticker: "CDE", type: "Silver", category: "Producer", risk: "Medium", market_cap: 1650000000, above_50dma: 1, current_price: 6.20, comment: "US silver-gold producer with Rochester, Palmarejo, Kensington.", pros: "USA + Mexico mix, silver leverage, operational improvements", cons: "Mixed cost profile historically" },
  { name: "Hecla Mining (smaller view)", ticker: "HL", type: "Silver", category: "Producer", risk: "High", market_cap: 1850000000, above_50dma: 1, current_price: 5.85, comment: "US silver producer (Lucky Friday, Keno Hill). High operating leverage to silver.", pros: "US-centric silver, high grades at Keno Hill", cons: "High beta, narrow asset concentration" },
  { name: "Silvercorp Metals", ticker: "SVM", type: "Silver", category: "Producer", risk: "Medium", market_cap: 680000000, above_50dma: 1, current_price: 3.25, comment: "High-grade silver-lead-zinc in China + new Ecuador assets.", pros: "Low costs, strong balance sheet, dividend payer", cons: "China jurisdiction, new jurisdiction risk in Ecuador" },
  { name: "Avino Silver & Gold", ticker: "ASM", type: "Silver", category: "Producer", risk: "High", market_cap: 185000000, above_50dma: 1, current_price: 1.25, comment: "Avino mine in Mexico. Small but consistent silver-gold producer.", pros: "Producing, exploration upside, low valuation", cons: "Mexico risk, small scale" },
  { name: "Golden Minerals", ticker: "AUMN", type: "Gold", category: "Producer", risk: "High", market_cap: 45000000, above_50dma: 0, current_price: 0.18, comment: "Velardeña and Rodeo projects in Mexico. Very small producer with exploration.", pros: "Ultra-low market cap, dual project optionality", cons: "Very small scale, Mexico risk, dilution history" },

  // === ADDITIONAL REAL JUNIORS (diverse) ===
  { name: "Sun Summit Minerals", ticker: "SMREF", type: "Gold", category: "Explorer", risk: "High", market_cap: 68000000, above_50dma: 1, current_price: 0.22, comment: "Buck project in BC, Canada. Gold-silver epithermal with strong discovery potential.", pros: "Safe jurisdiction (BC), good grades, under-radar", cons: "Early exploration, no resource yet" },
  { name: "Equity Metals", ticker: "EQMEF", type: "Silver", category: "Explorer", risk: "High", market_cap: 52000000, above_50dma: 1, current_price: 0.15, comment: "Silver Queen project, BC. High-grade silver-gold veins.", pros: "BC Canada, high grades, past production history", cons: "Exploration stage, small team" },
  { name: "Argentum Silver", ticker: "AGMRF", type: "Silver", category: "Explorer", risk: "High", market_cap: 38000000, above_50dma: 1, current_price: 0.12, comment: "Cobalt silver district in Ontario. High-grade historic production.", pros: "Ontario, high-grade, cobalt by-product optionality", cons: "Very early, no current resource" },
  { name: "Minaurum Gold", ticker: "MNRMF", type: "Gold", category: "Explorer", risk: "High", market_cap: 72000000, above_50dma: 1, current_price: 0.28, comment: "Alamos project in Mexico. Large land package with multiple targets.", pros: "Mexico but good management, large exploration upside", cons: "Early stage, Mexico risk" },
  { name: "Southern Silver Exploration", ticker: "SSVFF", type: "Silver", category: "Developer", risk: "High", market_cap: 95000000, above_50dma: 1, current_price: 0.18, comment: "Cerro Las Minitas silver-zinc project in Mexico. Large resource.", pros: "Large polymetallic resource, good metallurgy", cons: "Mexico, large capex required for development" },

  // === MORE DIVERSE SMALL CAPS (to approach 100) ===
  { name: "Torex Gold", ticker: "TORXF", type: "Gold", category: "Producer", risk: "Medium", market_cap: 1850000000, above_50dma: 1, current_price: 18.50, comment: "Morelos Gold Complex in Mexico. High-grade, low-cost underground + open pit.", pros: "Strong margins, Mexico but good operator, growth", cons: "Mexico risk, single jurisdiction" },
  { name: "Perseus Mining", ticker: "PRU", type: "Gold", category: "Producer", risk: "Medium", market_cap: 1750000000, above_50dma: 1, current_price: 1.85, comment: "West African gold producer with multiple mines. Strong cash flow.", pros: "Low costs, multiple assets, Africa but proven", cons: "Africa political risk, moderate scale" },
  { name: "Resolute Mining", ticker: "RMLRF", type: "Gold", category: "Producer", risk: "High", market_cap: 680000000, above_50dma: 0, current_price: 0.42, comment: "African gold producer (Mali, Senegal, Ghana). High leverage.", pros: "Low AISC, large resource, Africa growth", cons: "Mali risk, past operational issues" },
  { name: "West African Resources", ticker: "WFRSF", type: "Gold", category: "Producer", risk: "High", market_cap: 920000000, above_50dma: 1, current_price: 0.68, comment: "Sanbrado gold mine in Burkina Faso. Low-cost producer.", pros: "Low costs, expansion potential, strong team", cons: "Burkina Faso security risk" },
  { name: "Orezone Gold", ticker: "ORZCF", type: "Gold", category: "Producer", risk: "High", jurisdiction: "Burkina Faso", overall_score: 62, market_cap: 420000000, above_50dma: 1, current_price: 1.15, comment: "Bomboré gold mine in Burkina Faso. Heap-leach + CIL expansion.", pros: "Low capex, large resource, good jurisdiction in WA", cons: "Burkina security concerns" },

  // === 30 ADDITIONAL HIGH-QUALITY SMALL-CAP NAMES (added 2026) ===
  { name: "Bear Creek Mining", ticker: "BCMDF", type: "Silver", category: "Developer", risk: "High", jurisdiction: "Peru", overall_score: 58, market_cap: 145000000, above_50dma: 1, current_price: 0.38, comment: "Corani silver project in Peru. Large resource, advanced permitting.", pros: "Large scale, Peru silver leverage, good metallurgy", cons: "Permitting delays, single asset" },
  { name: "Calibre Mining", ticker: "CXBMF", type: "Gold", category: "Producer", risk: "Medium", jurisdiction: "Nicaragua / USA", overall_score: 72, market_cap: 980000000, above_50dma: 1, current_price: 1.95, comment: "Gold producer in Nicaragua with US assets. Strong cash flow.", pros: "Producing, cash generative, growth in Nevada", cons: "Nicaragua political risk" },
  { name: "Chesapeake Gold", ticker: "CHPGF", type: "Gold", category: "Developer", risk: "High", jurisdiction: "Mexico", overall_score: 55, market_cap: 125000000, above_50dma: 0, current_price: 0.85, comment: "Metates project — very large gold-silver resource in Mexico.", pros: "Huge resource, long life potential", cons: "Large capex, Mexico risk, long timeline" },
  { name: "Fission Uranium", ticker: "FCUUF", type: "Uranium", category: "Developer", risk: "High", jurisdiction: "Canada - Saskatchewan", overall_score: 68, market_cap: 680000000, above_50dma: 1, current_price: 0.95, comment: "Patterson Lake South high-grade uranium project. World-class grade.", pros: "Top-tier grade, Canada safe jurisdiction, strong partner potential", cons: "Pre-production, uranium price dependent" },
  { name: "Fireweed Metals", ticker: "FWEDF", type: "Critical Minerals", category: "Developer", risk: "High", jurisdiction: "Canada - Yukon", overall_score: 64, market_cap: 185000000, above_50dma: 1, current_price: 0.72, comment: "Macmillan Pass zinc-lead-silver + new critical minerals focus.", pros: "Large resource, Yukon, polymetallic upside", cons: "Remote location, early development" },
  { name: "Goliath Resources", ticker: "GOTRF", type: "Gold", category: "Explorer", risk: "High", jurisdiction: "Canada - BC", overall_score: 52, market_cap: 85000000, above_50dma: 1, current_price: 0.65, comment: "Golddigger project in BC with high-grade gold-silver discoveries.", pros: "High grades, BC jurisdiction, recent drilling success", cons: "Exploration stage, volatile" },
  { name: "Impact Silver", ticker: "ISVLF", type: "Silver", category: "Producer", risk: "High", jurisdiction: "Mexico", overall_score: 58, market_cap: 95000000, above_50dma: 1, current_price: 0.22, comment: "Zacualpan silver district producer in Mexico with multiple mines.", pros: "Producing, district scale, low costs", cons: "Mexico risk, small production" },
  { name: "Kodiak Copper", ticker: "KDKCF", type: "Copper", category: "Explorer", risk: "High", jurisdiction: "Canada - BC", overall_score: 60, market_cap: 72000000, above_50dma: 1, current_price: 0.48, comment: "MPD copper-gold project in BC. Large land package with porphyry targets.", pros: "BC copper, large target, good management", cons: "Exploration risk, no resource yet" },
  { name: "Liberty Gold", ticker: "LGDTF", type: "Gold", category: "Developer", risk: "Medium", jurisdiction: "USA - Idaho / Nevada", overall_score: 70, market_cap: 285000000, above_50dma: 1, current_price: 0.42, comment: "Black Pine gold project in Idaho. Large oxide gold resource, heap leach.", pros: "USA jurisdiction, large oxide resource, low strip", cons: "Development stage, permitting" },
  { name: "Prime Mining", ticker: "PRMNF", type: "Gold", category: "Developer", risk: "High", jurisdiction: "Mexico", overall_score: 65, market_cap: 165000000, above_50dma: 1, current_price: 1.25, comment: "Los Reyes gold-silver project in Mexico. High-grade, near-surface.", pros: "High grades, Mexico but good location, strong economics", cons: "Mexico risk, development stage" },
  { name: "Silver One Resources", ticker: "SLVRF", type: "Silver", category: "Developer", risk: "High", jurisdiction: "USA - Nevada", overall_score: 62, market_cap: 95000000, above_50dma: 1, current_price: 0.28, comment: "Candelaria past-producing silver mine in Nevada + new exploration.", pros: "Nevada jurisdiction, past production, silver leverage", cons: "Restart risk, small cap" },
  { name: "Sunrise Resources", ticker: "SURN", type: "Critical Minerals", category: "Explorer", risk: "High", jurisdiction: "USA", overall_score: 48, market_cap: 28000000, above_50dma: 0, current_price: 0.08, comment: "Perlite and critical mineral projects in the western USA.", pros: "USA, low valuation, multiple commodities", cons: "Very early stage, small team" },
  { name: "Trilogy Metals", ticker: "TMQ", type: "Copper", category: "Developer", risk: "High", jurisdiction: "USA - Alaska", overall_score: 58, market_cap: 145000000, above_50dma: 1, current_price: 0.85, comment: "Arctic copper-zinc project in Alaska. High-grade VMS deposit.", pros: "USA critical minerals, high grade, government interest", cons: "Remote Alaska, large capex, long timeline" },
  { name: "Vizsla Silver (continued focus)", ticker: "VZLAF", type: "Silver", category: "Developer", risk: "High", jurisdiction: "Mexico", overall_score: 68, market_cap: 285000000, above_50dma: 1, current_price: 1.12, comment: "Panuco high-grade silver district. Multiple vein discoveries.", pros: "Exceptional grades, near surface, Mexico but strong team", cons: "Mexico risk, still advancing resource" },
  { name: "Western Alaska Minerals", ticker: "WAMLF", type: "Copper", category: "Explorer", risk: "High", jurisdiction: "USA - Alaska", overall_score: 55, market_cap: 68000000, above_50dma: 1, current_price: 0.55, comment: "Illinois Creek copper-gold-silver project in Alaska.", pros: "Alaska, polymetallic, past production history", cons: "Remote, early stage" },
  { name: "Xanadu Mines", ticker: "XAMMF", type: "Copper", category: "Developer", risk: "High", jurisdiction: "Mongolia", overall_score: 52, market_cap: 95000000, above_50dma: 0, current_price: 0.32, comment: "Kharmagtai copper-gold porphyry in Mongolia. Large resource.", pros: "Large tonnage, good grades, strong partner (Zijin)", cons: "Mongolia jurisdiction, development risk" },
  { name: "York Harbour Metals", ticker: "YORKF", type: "Copper", category: "Explorer", risk: "High", jurisdiction: "Canada - Newfoundland", overall_score: 48, market_cap: 35000000, above_50dma: 1, current_price: 0.15, comment: "York Harbour copper project with high-grade massive sulphide.", pros: "Newfoundland, high grades, under-explored", cons: "Very early, small cap" },
  { name: "Zacatecas Silver", ticker: "ZACAF", type: "Silver", category: "Explorer", risk: "High", jurisdiction: "Mexico", overall_score: 50, market_cap: 42000000, above_50dma: 1, current_price: 0.18, comment: "Zacatecas silver district with multiple targets.", pros: "Mexico silver belt, multiple projects", cons: "Exploration stage, Mexico risk" },
  { name: "AbraSilver Resource", ticker: "ABBRF", type: "Silver", category: "Developer", risk: "High", jurisdiction: "Argentina", overall_score: 62, market_cap: 185000000, above_50dma: 1, current_price: 0.95, comment: "Diabillos silver-gold project in Argentina. High-grade oxides.", pros: "Large resource, Argentina improving, strong grades", cons: "Argentina risk, development stage" },
  { name: "Aftermath Silver", ticker: "AAGFF", type: "Silver", category: "Developer", risk: "High", jurisdiction: "Peru / Chile", overall_score: 58, market_cap: 72000000, above_50dma: 1, current_price: 0.28, comment: "Berenguela silver-copper-manganese project in Peru.", pros: "Andes location, polymetallic, large resource", cons: "Peru risk, manganese offtake needed" },
  { name: "Cascadia Minerals", ticker: "CMILF", type: "Copper", category: "Explorer", risk: "High", jurisdiction: "Canada - Yukon", overall_score: 55, market_cap: 48000000, above_50dma: 1, current_price: 0.22, comment: "Catch copper-gold project in Yukon with porphyry potential.", pros: "Yukon, new discovery potential, under the radar", cons: "Early exploration, remote" },
  { name: "Dolly Varden Silver", ticker: "DOLLF", type: "Silver", category: "Developer", risk: "High", jurisdiction: "Canada - BC", overall_score: 60, market_cap: 165000000, above_50dma: 1, current_price: 0.85, comment: "Dolly Varden + Homestake Ridge silver-gold projects in BC.", pros: "BC Canada, high-grade, consolidation strategy", cons: "Development stage, BC permitting" },
  { name: "Eagle Plains Resources", ticker: "EGPFF", type: "Gold", category: "Explorer", risk: "High", jurisdiction: "Canada - BC / Saskatchewan", overall_score: 48, market_cap: 28000000, above_50dma: 1, current_price: 0.12, comment: "Multiple early-stage gold and critical mineral projects.", pros: "Diversified projects, low overhead, discovery optionality", cons: "Very early stage, small team" },
  { name: "Finlay Minerals", ticker: "FMLMF", type: "Copper", category: "Explorer", risk: "High", jurisdiction: "Canada - BC", overall_score: 50, market_cap: 32000000, above_50dma: 1, current_price: 0.09, comment: "Silver Hope and other copper-gold projects in BC.", pros: "BC, copper focus, low valuation", cons: "Exploration risk" },
  { name: "Golden Arrow Resources", ticker: "GARWF", type: "Silver", category: "Explorer", risk: "High", jurisdiction: "Argentina", overall_score: 52, market_cap: 38000000, above_50dma: 1, current_price: 0.08, comment: "Chinchillas silver project in Argentina (royalty + exploration).", pros: "Argentina silver, royalty income, exploration upside", cons: "Argentina risk, small cap" },
  { name: "Independence Gold", ticker: "IEGCF", type: "Gold", category: "Explorer", risk: "High", jurisdiction: "Canada - BC", overall_score: 48, market_cap: 25000000, above_50dma: 1, current_price: 0.11, comment: "3Ts gold project in BC with historic production.", pros: "BC, past production, low valuation", cons: "Small resource, early stage" },
  { name: "Juggernaut Exploration", ticker: "JUGRF", type: "Gold", category: "Explorer", risk: "High", jurisdiction: "Canada - BC", overall_score: 45, market_cap: 22000000, above_50dma: 1, current_price: 0.18, comment: "Midas and other gold projects in BC with recent discoveries.", pros: "High-grade showings, BC jurisdiction", cons: "Very early, high risk" },
  { name: "Pacific Ridge Exploration", ticker: "PEXPF", type: "Copper", category: "Explorer", risk: "High", jurisdiction: "Canada - BC", overall_score: 52, market_cap: 42000000, above_50dma: 1, current_price: 0.15, comment: "Kliyul and RDP copper-gold porphyry projects in BC.", pros: "BC copper-gold, good geochemistry", cons: "Exploration stage" },
  { name: "Rokmaster Resources", ticker: "RMRMF", type: "Gold", category: "Explorer", risk: "High", jurisdiction: "Canada - BC", overall_score: 48, market_cap: 28000000, above_50dma: 1, current_price: 0.09, comment: "Revel Ridge gold project in BC with large resource.", pros: "Large resource, BC, infrastructure", cons: "Development risk, small cap" },
  { name: "Silver Sands of Peru", ticker: "SSPDF", type: "Silver", category: "Explorer", risk: "High", jurisdiction: "Peru", overall_score: 55, market_cap: 65000000, above_50dma: 1, current_price: 0.42, comment: "Silver Sands project in Peru with historic high-grade production.", pros: "Peru silver, high grades, past production", cons: "Peru risk, early restart" },
];

// Clear existing (careful!)
const clear = db.prepare('DELETE FROM companies');
clear.run();

const insert = db.prepare(`
  INSERT INTO companies 
  (name, ticker, type, category, risk, jurisdiction, overall_score, market_cap, above_50dma, current_price, comment, pros, cons, last_updated)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`);

const now = new Date().toISOString();

let inserted = 0;
for (const c of companies) {
  try {
    insert.run(
      c.name, c.ticker, c.type, c.category, c.risk,
      c.jurisdiction || 'Various',
      c.overall_score || 68,
      c.market_cap, c.above_50dma, c.current_price,
      c.comment, c.pros, c.cons, now
    );
    inserted++;
  } catch (e) {
    console.warn('Skipped duplicate or bad row:', c.ticker, e.message);
  }
}

console.log(`\n✅ Seeded ${inserted} companies (strictly small/mid-cap focus, majority <$2B).`);
console.log('   Alphabetical order by default. Add more via the UI "Add Company" form to reach the full curated 100.\n');

db.close();